baseURL = "https://blog.stevelongoria.net/"
languageCode = "en-us"
title = "Steve Longoria's Blog"
theme = "hugo-PaperMod"

[permalinks]
  posts = "/:year/:month/:day/:title/"

[params]
description = "Testing"
author = "Steve"
ShowReadingTime = true
defaultTheme = "auto"
ShowShareButtons = true

  [params.profileMode]
  enabled = false
  title = "Digital Marketing & Sales Copywriting Blog"
  imageUrl = "/steve.jpg"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Digital Marketing & Sales Copywriting Blog"
  Content = "Welcome"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/stevelongoria"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/longoriasteve"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/SteveLongoria"

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 10
