[[redirects]]
  from = "/2020/10/22/b2b-mobile-website-page-speed/"
  to = "https://freak.marketing/b2b-mobile-website-page-speed/"
[[redirects]]
  from = "/2019/03/10/how-to-setup-a-ghost-blog-contact-form/"
  to = "https://freak.marketing/how-to-setup-a-ghost-blog-contact-form/"
[[redirects]]
  from = "/2019/02/26/setup-stripe-checkout-using-expressjs-heroku/"
  to = "https://freak.marketing/how-to-setup-stripe-checkout-using-express-js-heroku/"
[[redirects]]
  from = "/tags/stripe/"
  to = "https://freak.marketing/tag/stripe/"
[[redirects]]
  from = "/2019/03/18/how-to-setup-stripe-elements-payment-form/"
  to = "https://freak.marketing/how-to-setup-stripe-elements-payment-form/"
[[redirects]]
  from = "/tags/payments/"
  to = "https://freak.marketing/tag/online-payments/"
[[redirects]]
  from = "/tags/handlebarsjs/"
  to = "https://freak.marketing/tag/web-development/"
[[redirects]]
  from = "/tags/expressjs/"
  to = "https://freak.marketing/tag/web-development/"
[[redirects]]
  from = "/2019/03/27/embed-instagram-feed-weebly-website/"
  to = "https://freak.marketing/embed-instagram-feed-weebly/"
[[redirects]]
  from = "/tags/instagram-feed/"
  to = "https://freak.marketing/tag/instagram/"
[[redirects]]
  from = "/tags/embed/"
  to = "https://freak.marketing/tag/web-development/"
[[redirects]]
  from = "/tags/website/"
  to = "https://freak.marketing/tag/web-development/"
[[redirects]]
  from = "/tags/weebly/"
  to = "https://freak.marketing/tag/weebly/"
[[redirects]]
  from = "/2018/07/28/drip-ghost-blog/"
  to = "https://freak.marketing/integrate-drip-into-your-ghost-blog/"
[[redirects]]
  from = "/tags/drip/"
  to = "https://freak.marketing/tag/email-marketing/"
[[redirects]]
  from = "/tags/ghost/"
  to = "https://freak.marketing/tag/ghost-blog/"
[[redirects]]
  from = "/tags/blog/"
  to = "https://freak.marketing/tag/blogging/"
[[redirects]]
  from = "/2019/02/15/how-long-does-it-take-to-get-organic-traffic/"
  to = "https://freak.marketing/how-long-generating-organic-google-traffic/"
[[redirects]]
  from = "/tags/google/"
  to = "https://freak.marketing/tag/google-serps/"
