[[redirects]]
  from = "/2020/10/22/b2b-mobile-website-page-speed/"
  to = "https://freak.marketing/b2b-mobile-website-page-speed/",
  from = "/2019/03/10/how-to-setup-a-ghost-blog-contact-form/"
  to = "https://www.stevelongoria.net/post/how-to-setup-a-ghost-blog-contact-form"
