[[redirects]]
  from = "/2020/10/22/b2b-mobile-website-page-speed/"
  to = "https://freak.marketing/b2b-mobile-website-page-speed/"
[[redirects]]
  from = "/2019/03/10/how-to-setup-a-ghost-blog-contact-form/"
  to = "https://freak.marketing/how-to-setup-a-ghost-blog-contact-form/"
[[redirects]]
  from = "/2019/02/26/setup-stripe-checkout-using-expressjs-heroku/"
  to = "https://freak.marketing/how-to-setup-stripe-checkout-using-express-js-heroku/"
[[redirects]]
  from = "/tags/stripe/"
  to = "https://freak.marketing/tag/stripe/"
[[redirects]]
  from = "/2019/03/18/how-to-setup-stripe-elements-payment-form/"
  to = "https://freak.marketing/how-to-setup-stripe-elements-payment-form/"
[[redirects]]
  from = "/tags/payments/"
  to = "https://freak.marketing/tag/online-payments/"
[[redirects]]
  from = "/tags/handlebarsjs/"
  to = "https://freak.marketing/tag/web-development/"
[[redirects]]
  from = "/tags/expressjs/"
  to = "https://freak.marketing/tag/web-development/"
[[redirects]]
  from = "/2019/03/27/embed-instagram-feed-weebly-website/"
  to = "https://freak.marketing/embed-instagram-feed-weebly/"
[[redirects]]
  from = "/tags/instagram-feed/"
  to = "https://freak.marketing/tag/instagram/"
[[redirects]]
  from = "/tags/embed/"
  to = "https://freak.marketing/tag/web-development/"
[[redirects]]
  from = "/tags/website/"
  to = "https://freak.marketing/tag/web-development/"
[[redirects]]
  from = "/tags/weebly/"
  to = "https://freak.marketing/tag/weebly/"
[[redirects]]
  from = "/2018/07/28/drip-ghost-blog/"
  to = "https://freak.marketing/integrate-drip-into-your-ghost-blog/"
[[redirects]]
  from = "/tags/drip/"
  to = "https://freak.marketing/tag/email-marketing/"
[[redirects]]
  from = "/tags/ghost/"
  to = "https://freak.marketing/tag/ghost-blog/"
[[redirects]]
  from = "/tags/blog/"
  to = "https://freak.marketing/tag/blogging/"
[[redirects]]
  from = "https://blog.stevelongoria.net/2019/02/15/how-long-does-it-take-to-get-organic-traffic/"
  to = "https://freak.marketing/how-long-generating-organic-google-traffic/"
[[redirects]]
  from = "/tags/google/"
  to = "https://freak.marketing/tag/google-serps/"
[[redirects]]
  from = "/2018/11/03/custom-drip-form-css-flexbox/"
  to = "https://freak.marketing/custom-drip-optin-form-css-flexbox/"
[[redirects]]
  from = "/tags/flexbox/"
  to = "https://freak.marketing/tag/flexbox/"
[[redirects]]
  from = "/tags/css/"
  to = "https://freak.marketing/tag/css/"
[[redirects]]
  from = "/tags/drip/"
  to = "https://freak.marketing/tag/drip/"
[[redirects]]
  from = "/tags/marketing/"
  to = "https://freak.marketing/tag/marketing-automation/"
[[redirects]]
  from = "/tags/automation/"
  to = "https://freak.marketing/tag/marketing-automation/"
[[redirects]]
  from = "/2020/02/08/integrate-memberstack-with-convertkit/"
  to = "https://freak.marketing/integrate-memberstack-with-convertkit/"
[[redirects]]
  from = "/tags/membership-sites/"
  to = "https://freak.marketing/tag/membership-site/"
[[redirects]]
  from = "/tags/memberstack/"
  to = "https://freak.marketing/tag/memberstack/"
[[redirects]]
  from = "/tags/convertkit/"
  to = "https://freak.marketing/tag/convertkit/"
[[redirects]]
  from = "/tags/marketing-automation/"
  to = "https://freak.marketing/tag/marketing-automation/"
[[redirects]]
  from = "/2019/02/08/add-twitter-share-button-to-hexo-blog-posts/"
  to = "https://freak.marketing/add-a-twitter-share-button-to-each-hexo-blog-post/"
[[redirects]]
  from = "/2019/08/14/facebook-messenger-ad-manychat-json-growth-tool/"
  to = "https://freak.marketing/tag/social-media-marketing/"
[[redirects]]
  from = "/tags/twitter/"
  to = "https://freak.marketing/tag/twitter/"
