[[redirects]]
  from = "/2020/10/22/b2b-mobile-website-page-speed/"
  to = "https://freak.marketing/b2b-mobile-website-page-speed/"
[[redirects]]
  from = "/2019/03/10/how-to-setup-a-ghost-blog-contact-form/"
  to = "https://freak.marketing/how-to-setup-a-ghost-blog-contact-form/"
[[redirects]]
  from = "/2019/02/26/setup-stripe-checkout-using-expressjs-heroku/"
  to = "https://freak.marketing/how-to-setup-stripe-checkout-using-express-js-heroku/"
[[redirects]]
  from = "/tags/stripe/"
  to = "https://www.stevelongoria.net/category/stripe"
[[redirects]]
  from = "/2019/03/18/how-to-setup-stripe-elements-payment-form/"
  to = "https://www.stevelongoria.net/post/how-to-setup-stripe-elements-payment-form"
[[redirects]]
  from = "/tags/payments/"
  to = "https://www.stevelongoria.net/category/stripe"
[[redirects]]
  from = "/tags/handlebarsjs/"
  to = "https://www.stevelongoria.net/category/web-development"
[[redirects]]
  from = "/tags/expressjs/"
  to = "https://www.stevelongoria.net/category/web-development"
[[redirects]]
  from = "/2019/03/27/embed-instagram-feed-weebly-website/"
  to = "https://www.stevelongoria.net/post/how-to-embed-your-instagram-feed-onto-your-weebly-website"
[[redirects]]
  from = "/tags/instagram-feed/"
  to = "https://www.stevelongoria.net/category/social-media-marketing"
[[redirects]]
  from = "/tags/embed/"
  to = "https://www.stevelongoria.net/category/web-development"
[[redirects]]
  from = "/tags/website/"
  to = "https://www.stevelongoria.net/category/web-development"
[[redirects]]
  from = "/tags/weebly/"
  to = "https://www.stevelongoria.net/category/web-development"
